repos:
- repo: https://github.com/psf/black
  rev: 21.8b0
  hooks:
    - id: black-jupyter
- repo: https://github.com/nbQA-dev/nbQA
  rev: 1.1.0
  hooks:
    - id: nbqa-isort
      additional_dependencies: [isort==5.6.4]
    - id: nbqa-pyupgrade
      additional_dependencies: [pyupgrade==2.7.4]
      args: [--py37-plus]
- repo: https://github.com/MarcoGorelli/check-execution-order
  rev: v0.1.1
  hooks:
    - id: check-execution-order
