project:
  type: book
  output-dir: docs

book:
  title: "Regression and Other Stories: Python Implementation"
  author: "Farhan Reynaldo"
  sidebar:
    style: docked
    background: light
  chapters:
    - index.md
    - part: "Chapter 10"
      chapters:
      - ros/ch10/kidiq.ipynb
      - ros/ch10/height_and_weight.ipynb
      - ros/ch10/beauty.ipynb
      - ros/ch10/congress.ipynb
      - ros/ch10/nes_linear.ipynb
  page-navigation: true
  footer:  
    right: 
      - icon: github
        href: https://github.com/farhanreynaldo
      - icon: twitter 
        href: https://twitter.com/xynx 

format:
  html:
    theme: 
      light: cosmo
      dark: darkly



